name: test
on: push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-11-arm, ubuntu-latest, macos-latest]
        luaVersion: ['git', '5.5', '5.4', '5.3', '5.2', '5.1']
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        luaVersion: ${{ matrix.luaVersion }}
    - run: lua -e "print(_VERSION)"
